version: '2'
services:
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
    - /share/CACHEDEV1_DATA/Container/postgresql:/var/lib/postgresql
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - /share/CACHEDEV1_DATA/Container/redis:/var/lib/redis
  gitlab:
    restart: always
    image: sameersbn/gitlab:10.7.2
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "10022:22"
    volumes:
    - /share/CACHEDEV1_DATA/Container/gitlab:/home/git/data
    environment:
    - DEBUG=false
    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_SECRETS_DB_KEY_BASE=qcs-gitlab-app
    - GITLAB_SECRETS_OTP_KEY_BASE=qcs-gitlab-app
    - GITLAB_SECRETS_SECRET_KEY_BASE=qcs-gitlab-app
    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=false
